### ISSUE TITLE
onclick with toggle triggers the same card in a dynamic flippy list 

### ISSUE THREAD

**Issue by ZUKAMZUKA** [sbayd/react-flippy#5]
![screenshot 4](https://user-images.githubusercontent.com/39775103/50215970-979a6800-0395-11e9-97b7-636677daebf7.png)
![screenshot 5](https://user-images.githubusercontent.com/39775103/50215972-979a6800-0395-11e9-8230-d09f47f8fc69.png)
![screenshot 6](https://user-images.githubusercontent.com/39775103/50215973-9832fe80-0395-11e9-946e-118ceaac0f8d.png)

**Comment by ZUKAMZUKA** [comment]
selected the toggle button on the first card... the last card was flipped and so on with the second and the third, they trigger the last card

**Comment by devPadre** [comment]
@ZUKAMZUKA Assuming that you are following the readme to set a ref for Flippy component -- like this: ref={(r) => this.flippy = r}.  Generally in react, refs aren't usually the preferred method. The reason this.flippy is set to the last element is because you are setting each element in the loop to this.flippy, so the last one overwrites the one before and so on.  Since .toggle() has been added as a method, you should be able to remove the ref in Flippy and simply trigger toggle for the element itself by simply creating a button in the Flip component with: onClick={() => this.toggle}  The Flip.js component already establishes what the execution context for "this" is, so this.toggle should simply execute the function in the Flip.js component.

**Comment by devPadre** [comment]
> selected the toggle button on the first card... the last card was flipped and so on with the second and the third, they trigger the last card

You need unique identifiers when using in a list - ideally you're using some data id from the cards in your list - otherwise since you are looping over everything you are just rewriting the value of the ref until every card has the same value - the last one.

```ref={(r) => this[`${item.id`] = r}  ...  
onClick={() => this[`${item.id}`].toggle()}```

**Comment by sbayd** [comment]
@ZUKAMZUKA @devPadre Thank you for your responses. 
The issue should be fixed with proper usage.
